---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collectd
  namespace: monitoring
data:
  collectd.conf: |-
    LoadPlugin cpu
    LoadPlugin memory
    LoadPlugin network
    LoadPlugin df
    LoadPlugin write_http
    LoadPlugin write_prometheus
    LoadPlugin logfile
    <Plugin "write_prometheus">
      Port "9103"
    </Plugin>
    <Plugin "cpu">
      Interval 5
      ReportByState false
      ReportByCpu false
    </Plugin>
    <Plugin "memory">
      Interval 30
      ValuesAbsolute false
      ValuesPercentage true
    </Plugin>
    <Plugin network>
      Server "localhost" "25826"
    </Plugin>
    <Plugin logfile>
      LogLevel info
      File "/var/log/collectd.log"
      Timestamp true
      PrintSeverity false
    </Plugin>
    <Plugin write_http>
      <Node "collectd_exporter">
        URL "http://localhost:9103/collectd-post"
        Format "JSON"
        StoreRates false
      </Node>
    </Plugin>
    \n