apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: collectd-exporter
  name: collectd
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: web
  jobLabel: k8s-app  
  selector:
    matchLabels:
      k8s-app: collectd-exporter
